version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"

  nestjs-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=
      - MONGO_URI=
      - FRONTEND_URL=
    depends_on:
      - mongo
